name: check
on: 
  workflow_dispatch:
env:
  PROVIDER_NAME: Westchester
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: check
      run: echo "aa=$(curl -s https://am-i-eligible.covid19vaccine.health.ny.gov/api/list-providers | jq '.providerList[] | select(.providerName | startswith("${{env.PROVIDER_NAME}}")) | .availableAppointments')" >> $GITHUB_ENV 
    - name: debug
      run: echo $aa
    - name: notify
      if: env.aa == '"AA"'
      run: curl 'https://api.twilio.com/2010-04-01/Accounts/${{secrets.TWILIO_ACCOUNTID}}/Messages.json' -X POST --data-urlencode 'To=whatsapp:${{secrets.PHONE_NUMBER}}' --data-urlencode 'From=whatsapp:${{secrets.TWILIO_PHONE_NUMBER}}' --data-urlencode 'Body=Appointments available in ${{env.PROVIDER_NAME}}' -u ${{secrets.TWILIO_TOKEN}}


