name: twitter
on: 
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: authorize
      run: docker run maxhorstmann/twurl authorize --consumer-key key --consumer-secret secret
    - name: tweet
      run: docker run maxhorstmann/twurl -d 'status=Hello world!' /1.1/statuses/update.json
