name: twitter
on: 
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: install twurl
      run: gem install --local twurl
    - name: authorize
      run: twurl authorize --consumer-key TODO --consumer-secret TODO


