name: twitter
on: 
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Fetch availabilities
      run: curl -s https://am-i-eligible.covid19vaccine.health.ny.gov/api/list-providers | jq '.providerList[] | select(.availableAppointments =="AA") | .address' > availabilities.txt
    - name: Config name
      run: git config user.name "Vaccine Bot"
    - name: Config email
      run: git config user.email "${{ secrets.EMAIL }}"
    - name: Add to repo
      run: git add availabilities.txt
    - name: Check if availabilities have changed
      id: check
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Availabilities have changed!"
          echo "::set-output name=changes::1"
        else
          echo "Availabilities haven't changed."
        fi 
    - name: Compose Tweet
      run: |
        TWEET="Appointments are now available in "
        FIRST=true
        while read p; do
          if [ "$FIRST" = true ] ; then
            FIRST=false
          else
            TWEET="${TWEET}, "
          fi
          TWEET="${TWEET}$p"
        done < availabilities.txt
        TWEET="${TWEET}: https://am-i-eligible.covid19vaccine.health.ny.gov"
        echo $TWEET
        echo "TWEET=$TWEET" >> $GITHUB_ENV

    - name: Tweet if availabilities changed
      if: steps.check.outputs.changes    
      run: |
        docker run maxhorstmann/twurl \
        -c ${{ secrets.TWITTER_CONSUMER_API_KEY }} \
        -s ${{ secrets.TWITTER_CONSUMER_API_SECRET }} \
        -a ${{ secrets.TWITTER_ACCESS_TOKEN }} \
        -S ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} \
        -d 'status=${{ env.TWEET }}' \
        /1.1/statuses/update.json
    - name: Commit changes
      if: steps.check.outputs.changes
      run: git commit -m "New availabilities"
    - name: Push changes
      if: steps.check.outputs.changes
      run: git push
