name: twitter
on: 
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: tweet
      run: |
        docker run maxhorstmann/twurl \
        -c ${{ secrets.TWITTER_CONSUMER_API_KEY }} \
        -s ${{ secrets.TWITTER_CONSUMER_API_SECRET }} \
        -a ${{ secrets.TWITTER_ACCESS_TOKEN }} \
        -S ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} \
        -d 'status=Hello from GitHub Actions!' \
        /1.1/statuses/update.json
